[build]
builder = "NIXPACKS"
buildCommand = "python -m pip install -r backend/requirements.txt"

[deploy]
startCommand = "python backend/main.py"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
